/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenunciasRouteImport } from './routes/denuncias'
import { Route as DenunciasProtocolRouteImport } from './routes/denuncias.$protocol'
import { Route as FotosIdRouteImport } from './routes/fotos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasRoute = DenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasProtocolRoute = DenunciasProtocolRouteImport.update({
  id: '/$protocol',
  path: '/$protocol',
  getParentRoute: () => DenunciasRoute,
} as any)
const FotosIdRoute = FotosIdRouteImport.update({
  id: '/fotos/$id',
  path: '/fotos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRouteWithChildren
  '/denuncias/$protocol': typeof DenunciasProtocolRoute
  '/fotos/$id': typeof FotosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRouteWithChildren
  '/denuncias/$protocol': typeof DenunciasProtocolRoute
  '/fotos/$id': typeof FotosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRouteWithChildren
  '/denuncias/$protocol': typeof DenunciasProtocolRoute
  '/fotos/$id': typeof FotosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/denuncias' | '/denuncias/$protocol' | '/fotos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/denuncias' | '/denuncias/$protocol' | '/fotos/$id'
  id: '__root__' | '/' | '/denuncias' | '/denuncias/$protocol' | '/fotos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenunciasRoute: typeof DenunciasRouteWithChildren
  FotosIdRoute: typeof FotosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias': {
      id: '/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof DenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias/$protocol': {
      id: '/denuncias/$protocol'
      path: '/$protocol'
      fullPath: '/denuncias/$protocol'
      preLoaderRoute: typeof DenunciasProtocolRouteImport
      parentRoute: typeof DenunciasRoute
    }
    '/fotos/$id': {
      id: '/fotos/$id'
      path: '/fotos/$id'
      fullPath: '/fotos/$id'
      preLoaderRoute: typeof FotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DenunciasRouteChildren {
  DenunciasProtocolRoute: typeof DenunciasProtocolRoute
}

const DenunciasRouteChildren: DenunciasRouteChildren = {
  DenunciasProtocolRoute: DenunciasProtocolRoute,
}

const DenunciasRouteWithChildren = DenunciasRoute._addFileChildren(
  DenunciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenunciasRoute: DenunciasRouteWithChildren,
  FotosIdRoute: FotosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
